/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bson.cross.json

import com.fasterxml.jackson.databind.*
import de.undercouch.bson4jackson.BsonFactory

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)

    examples()
}


fun examples() {
    val m = mapOf("hello" to "world")
    printAsBson(m)
    printAsJson(m)
}

fun printAsBson(m: Map<String, String>) {
    val bsonMapper = ObjectMapper(BsonFactory())
    val bytes = bsonMapper.writeValueAsBytes(m)

    val formatter = { index: Int, byte: Byte ->
        "0x%02x 0x%02x".format(index, byte)
    }
    bytes.forEachIndexed { index, byte -> println(formatter(index, byte))}
}

fun printAsJson(m: Map<String, String>) {
    val jsonMapper = ObjectMapper()
    jsonMapper.writeValue(System.out, m)
}


