/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bson.cross.json

import java.io.*
import com.fasterxml.jackson.databind.*
import de.undercouch.bson4jackson.*

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)

    exampleBsonCrossJson()
}


fun exampleBsonCrossJson() {

    val m = mapOf("hello" to "world")
    val bsonMapper = ObjectMapper(BsonFactory())

    bsonMapper.writeValue(System.out, m)

    val jsonMapper = ObjectMapper()
    jsonMapper.writeValue(System.out, m)
}



